AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'test/**/*'
    - 'deploy/*'
    - '**/Gemfile'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/environments/**'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'
    - 'config/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/models/scenario_spec.rb'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%i': '[]'

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/models/scenario_spec.rb'
