test:
  adapter: postgresql
  pool: 5
  database: innoz_rails_test

development:
  adapter: postgresql
  pool: 5
  database: innoz_rails_development

production:
  adapter: postgresql
  pool: 5
  database: innoz_rails_production
