test:
  adapter: postgis
  pool: 5
  database: mas_interface_test

development:
  adapter: postgis
  user: postgres
  password: postgres
  pool: 5
  database: mas_interface_development

production:
  adapter: postgis
  pool: 5
  database: mas_interface_production
