test:
  adapter: postgresql
  pool: 5
  database: mas_interface_test

development:
  adapter: postgresql
  pool: 5
  database: mas_interface_development

production:
  adapter: postgresql
  pool: 5
  database: mas_interface_production
